/*
Problem 2 - Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Solution - 4613732
*/
package main

import "fmt"

const (
	limit = 4000000
)

func main() {
	sum := 0
	for a, b := 0, 1; b < limit; a, b = b, a + b {
		if b % 2 == 0 {
			sum += b;
		}
	}

	fmt.Printf("%d\n", sum)
}
